import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const SEED_CREATORS = [
  {
    instagramHandle: "vasai_foodie",
    fullName: "Priya Sharma",
    city: "Mumbai",
    area: "Vasai",
    nicheTags: '["Food","Cafe"]',
    followerCount: 4200,
    avgEngagementRate: 8.2,
    estimatedRateMin: 600,
    estimatedRateMax: 1200,
    contactMethod: "dm_only",
    contactValue: "DM only",
    lastVerifiedDate: new Date("2026-06-18"),
    profilePicUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya&backgroundColor=f0e8dc",
    accountType: "Creator",
    isVerifiedActive: true,
    recentPostCountChecked: 6,
    avgLikes: 340,
    avgComments: 28,
    contentStyle: "Reels-only",
    previousBrandCollabs: "Cafe Mocha Vasai",
    language: '["Hindi","English"]',
    sourceFound: "Hashtag #vasaifood",
    notes: "Responsive, good engagement",
  },
  {
    instagramHandle: "virar_bites",
    fullName: "Rahul Mehta",
    city: "Mumbai",
    area: "Virar",
    nicheTags: '["Food","Desserts"]',
    followerCount: 8900,
    avgEngagementRate: 7.5,
    estimatedRateMin: 800,
    estimatedRateMax: 1500,
    contactMethod: "email",
    contactValue: "rahul.mehta@email.com",
    lastVerifiedDate: new Date("2026-06-20"),
    profilePicUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=rahul&backgroundColor=e8a090",
    accountType: "Personal",
    isVerifiedActive: true,
    recentPostCountChecked: 6,
    avgLikes: 520,
    avgComments: 45,
    contentStyle: "Mix",
    language: '["Hindi","Marathi","English"]',
    sourceFound: "Hashtag #virarfood",
  },
  {
    instagramHandle: "sweet_tooth_vv",
    fullName: "Ananya Patel",
    city: "Mumbai",
    area: "Vasai",
    nicheTags: '["Desserts","Cafe"]',
    followerCount: 15600,
    avgEngagementRate: 6.8,
    estimatedRateMin: 1200,
    estimatedRateMax: 2500,
    contactMethod: "whatsapp",
    contactValue: "+91 98765 43210",
    lastVerifiedDate: new Date("2026-06-15"),
    profilePicUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=ananya&backgroundColor=a8c4ac",
    accountType: "Creator",
    isVerifiedActive: true,
    contentStyle: "Reels-only",
    previousBrandCollabs: "Sweet Crumbs Bakery, Dolce Vasai",
    language: '["English","Hindi"]',
    sourceFound: "Manual outreach",
  },
  {
    instagramHandle: "nalasopara_eats",
    fullName: "Karan Singh",
    city: "Mumbai",
    area: "Nalasopara",
    nicheTags: '["Food"]',
    followerCount: 3200,
    avgEngagementRate: 9.1,
    estimatedRateMin: 500,
    estimatedRateMax: 900,
    contactMethod: "dm_only",
    contactValue: "DM only",
    lastVerifiedDate: new Date("2026-06-19"),
    profilePicUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=karan&backgroundColor=f0e8dc",
    accountType: "Personal",
    isVerifiedActive: true,
    recentPostCountChecked: 6,
    avgLikes: 290,
    avgComments: 22,
    contentStyle: "Mix",
    language: '["Hindi"]',
    sourceFound: "Hashtag #nalasoparafood",
  },
  {
    instagramHandle: "cloud_kitchen_diaries",
    fullName: "Amit Joshi",
    city: "Mumbai",
    area: "Virar",
    nicheTags: '["Food"]',
    followerCount: 6800,
    avgEngagementRate: 7.9,
    estimatedRateMin: 700,
    estimatedRateMax: 1300,
    contactMethod: "email",
    contactValue: "amit.joshi@gmail.com",
    lastVerifiedDate: new Date("2026-06-17"),
    profilePicUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=amit&backgroundColor=a8c4ac",
    accountType: "Creator",
    isVerifiedActive: true,
    contentStyle: "Reels-only",
    language: '["Hindi","English"]',
    sourceFound: "Referral",
    notes: "Specializes in cloud kitchen reviews",
  },
  {
    instagramHandle: "virar_sweet_spot",
    fullName: "Pooja Kulkarni",
    city: "Mumbai",
    area: "Virar",
    nicheTags: '["Desserts"]',
    followerCount: 5400,
    avgEngagementRate: 8.7,
    estimatedRateMin: 650,
    estimatedRateMax: 1100,
    contactMethod: "dm_only",
    contactValue: "DM only",
    lastVerifiedDate: new Date("2026-06-20"),
    profilePicUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=pooja&backgroundColor=f0e8dc",
    accountType: "Personal",
    isVerifiedActive: true,
    recentPostCountChecked: 6,
    avgLikes: 380,
    avgComments: 31,
    contentStyle: "Reels-only",
    language: '["Marathi","Hindi"]',
    sourceFound: "Hashtag #virarsweets",
  },
];

async function main() {
  console.log("Seeding database...");
  for (const creator of SEED_CREATORS) {
    await prisma.creator.upsert({
      where: { instagramHandle: creator.instagramHandle },
      update: creator,
      create: creator,
    });
  }
  console.log(`Seeded ${SEED_CREATORS.length} creators.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
